### ISSUE TITLE
Issue Fetching Transactions from Plaid Account

### ISSUE THREAD

**Issue by willwrong** [connorbenton/fin#2]
I'm encountering an issue when I try to scan in transaction/info from Plaid. The account has been added successfully (and the total $$$ is showing on the main screen), but when I hit Fetch Transactions For All Accounts it bounces straight out. Logs reveal the following:

`2020/06/17 14:57:47 Error with Create Token Client Get Accounts request: /accounts/get - access token must be specified

panic: /accounts/get - access token must be specified

goroutine 103 [running]:
fin-go/routes/plaid.RefreshConnection(0x1, 0xc005bd0180, 0x2a, 0x0, 0x0, 0x0, 0x0, 0xc0058804b8, 0x5, 0x0, ...)
	/usr/src/app/backend_go/routes/plaid/plaid.go:251 +0xabe
fin-go/routes/itemTokens.FetchTransactionsFunction.func1.3(0xc0058804f0, 0xc00588005d, 0xc00524a510, 0xc00524a570, 0x1, 0xc005bd0180, 0x2a, 0x0, 0x0, 0x0, ...)
	/usr/src/app/backend_go/routes/itemTokens/itemTokens.go:85 +0x1df
created by fin-go/routes/itemTokens.FetchTransactionsFunction.func1
	/usr/src/app/backend_go/routes/itemTokens/itemTokens.go:82 +0x5dd
runtime: note: your Linux kernel may be buggy
runtime: note: see https://golang.org/wiki/LinuxKernelSignalVectorBug
runtime: note: mlock workaround for kernel bug failed with errno 12`

This is using your docker container and following the instructions listed.

I'm also unable to even begin trying to add a Saltedge account (stating "ConnectURL field empty) but I'll fork that into a separate issue when I have a minute.

Good luck with the project, seems very promising so far!

**Comment by connorbenton** [comment]
- Can you post your (sanitized) environment variable file?
- Was this using development or sandbox? 
- Are there any other errors in the container's docker log? The same Plaid API endpoint is called in the same way on line 101 in plaid.go during the initial connection import (once you've entered your credentials), so it's strange that it didn't flag the same access token missing error there.

**Comment by willwrong** [comment]
- The environment variable file (if sanitized) would be identical to your .env sample file. All I did was copy paste in my keys.

- It turns out I am getting an "access token must be specificed" event upon adding an account via Plaid:

`2020/06/18 00:09:13 Error with Create Token Client Get Accounts request: /accounts/get - access token must be specified. Exact same error message as above.

What's strange is that the account is successfully adding, so the API is half working -- just then not able to pull transaction info after that stage.

**Comment by connorbenton** [comment]
> The environment variable file (if sanitized) would be identical to your .env sample file. All I did was copy paste in my keys.

OK, so then this is in the sandbox environment, correct?

Can you cd to your db directory on your machine and run:
`sqlite3 data-go.sqlite 'select * from item_tokens;'`
You should be getting just one line per connection you've made, with a value in the third column like 'access-sandbox-XXXX', let me know if that's missing.

Are there any other errors in the docker log anywhere, and if so can you copy the full trace as you did above?

**Comment by willwrong** [comment]
> OK, so then this is in the sandbox environment, correct?

This could be where I'm confused -- when I use Sandbox, it doesn't actually allow me to add any accounts, just a "test" account. So I switched to development, which allows me to add an account, but not import any financial data from it (besides the current account total amount).

I also ran that command, and I didn't get anything back... But that may be because I reset the database earlier while playing around with it!

No other errors that I can see, besides the afforementioned one with SaltEdge having no connectURL.

**Comment by willwrong** [comment]
Okay, I may have fixed it by completely rebuilding and setting permissions to 777 (not ideal but fine in this environment). But I am now seeing my financial data and the analysis page.

Any ideas as to why, with correct API keys, the SaltEdge import would be throwing the "no ConnectURL" alert?

**Comment by connorbenton** [comment]
> Any ideas as to why, with correct API keys, the SaltEdge import would be throwing the "no ConnectURL" alert?

You've created just one [Customer](https://www.saltedge.com/clients/customers) for your account (and populated the environment file with that customer ID), correct? Are you already upgraded to test access with SaltEdge?

**Comment by willwrong** [comment]
Exactly, it's all exactly as per my Saltedge dashboard, but it doesn't seem to respond to anything from within Fin. And yes, I'm on test access. Odd stuff !

**Comment by connorbenton** [comment]
Are you using an App Key or a [Service Key](https://www.saltedge.com/clients/profile/secrets)?

**Comment by willwrong** [comment]
App key -- would this be incorrect of me?

**Comment by connorbenton** [comment]
Ah yeah, I believe you need a service key - can you try to create one (you can leave the public key value blank) and restart the container with those values in the env file?

**Comment by willwrong** [comment]
Yeah that's fixed it... silly old me!

Might be worth adding that to the documentation so that idiots like me don't screw it up in future ;-) 

Thanks for all your help... Really neat little container so far, will be interested to see what functionality you add to it.

**Comment by connorbenton** [comment]
No problem, I definitely should have made that clearer in the documentation - I'll make a pull request for the readme so I can reference this one, thanks for your help!
