### ISSUE TITLE
Dummy Bank and Manual Transactions

### ISSUE THREAD

**Issue by nicoolaro** [connorbenton/fin#3]
Hi is it possible to add feature for manual transactions (also recurring) and Dummy Banks(Accounts) or Budgets .
I would like to use the app but my Bank does not support Saltedge and Plaid, and no CSV export unfortunately.

Thanks

**Comment by connorbenton** [comment]
I wrote this project specifically to have a tracker that didn't have any manual input or budgeting whatsoever, just a purely automatic expense tracker - apologies that it doesn't align more with your interests, I'll reopen this issue if the project ever moves in that direction.
